name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello Gh Actions!
      - name: Print few lines
        run: |
          echo Firts line
          echo Second line
